### ISSUE TITLE
Old rdpwrap.ini

### ISSUE THREAD

**Issue by fragtion** [LCW0NJUPT/rdpwrap-autoupdate#1]
This upgrade script is really basically a downgrade script at the moment, as the repo's for the updated rdpwrap.ini both haven't been updated in years

For example, 10.0.18362.778 is missing from both forks

Regards

**Comment by LCW0NJUPT** [comment]
Hello @fragtion ,
This upgrade script downloads rdpwrap.ini from [asmtron's project](https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini)，which updated only 6 hours ago and added support for 10.0.18362.836 (x64).

There is no 10.0.18362.778 in these scripts, but it can be adapted to the latest Windows 10. You can try to add 10.0.18362.778 manually into the .ini file, or update windows to the latest version.

Hope this will solve your problem.

Thanks
![asmtron](https://user-images.githubusercontent.com/27960628/81935526-59a18200-9623-11ea-9cdb-965d4af034fa.png)

**Comment by fragtion** [comment]
@LCW0NJUPT That is good to hear, Thanks for confirming! I will try it :)
